
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing dispatch graph mode")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_DISPATCH_GRAPH_MODE_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/dispatch_graph_mode.hpp")
NCPP_SetGlobal(NRHI_DISPATCH_GRAPH_MODE_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/dispatch_graph_mode.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_dispatch_graph_mode"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_DISPATCH_GRAPH_MODE_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_DISPATCH_GRAPH_MODE_ENUM_CPP_FILE_PATH}"
    VALUES
        NODE_CPU_INPUT D3D12_DISPATCH_MODE_NODE_CPU_INPUT
        NODE_GPU_INPUT D3D12_DISPATCH_MODE_NODE_GPU_INPUT
        MULTI_NODE_CPU_INPUT D3D12_DISPATCH_MODE_MULTI_NODE_CPU_INPUT
        MULTI_NODE_GPU_INPUT D3D12_DISPATCH_MODE_MULTI_NODE_GPU_INPUT
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement dispatch graph mode done")