
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing resource bind flag")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_RESOURCE_BIND_FLAG_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_bind_flag.hpp")
NCPP_SetGlobal(NRHI_RESOURCE_BIND_FLAG_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_bind_flag.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_resource_bind_flag"
    TYPE "ncpp::u32"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_RESOURCE_BIND_FLAG_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_RESOURCE_BIND_FLAG_ENUM_CPP_FILE_PATH}"
    VALUES
        NONE "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0, 0)"
        VBV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x1, 0)"
        INSTBV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x2, 0)"
        IBV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x4, 0)"
        CBV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x8, 0)"
        SRV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x10, 0)"
        UAV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x20, D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS)"
        RTV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x40, D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET)"
        DSV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x80, D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL)"
        CROSS_ADAPTER "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x100, D3D12_RESOURCE_FLAG_ALLOW_CROSS_ADAPTER)"
        SIMULTANEOUS "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x200, D3D12_RESOURCE_FLAG_ALLOW_SIMULTANEOUS_ACCESS)"
        VIDEO_DECODE_REFERENCE_ONLY "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x400, D3D12_RESOURCE_FLAG_VIDEO_DECODE_REFERENCE_ONLY)"
        VIDEO_ENCODE_REFERENCE_ONLY "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x800, D3D12_RESOURCE_FLAG_VIDEO_ENCODE_REFERENCE_ONLY)"
        RAYTRACING_ACCELERATION_STRUCTURE "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0x1000, D3D12_RESOURCE_FLAG_RAYTRACING_ACCELERATION_STRUCTURE)"
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement resource bind flag done")