
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing indirect argument type")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_INDIRECT_ARGUMENT_TYPE_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/indirect_argument_type.hpp")
NCPP_SetGlobal(NRHI_INDIRECT_ARGUMENT_TYPE_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/indirect_argument_type.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_indirect_argument_type"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_INDIRECT_ARGUMENT_TYPE_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_INDIRECT_ARGUMENT_TYPE_ENUM_CPP_FILE_PATH}"
    VALUES
        DRAW_INSTANCED D3D12_INDIRECT_ARGUMENT_TYPE_DRAW
        DRAW_INDEXED_INSTANCED D3D12_INDIRECT_ARGUMENT_TYPE_DRAW_INDEXED
        DISPATCH D3D12_INDIRECT_ARGUMENT_TYPE_DISPATCH
        INPUT_BUFFER D3D12_INDIRECT_ARGUMENT_TYPE_VERTEX_BUFFER_VIEW
        INDEX_BUFFER D3D12_INDIRECT_ARGUMENT_TYPE_INDEX_BUFFER_VIEW
        CONSTANTS D3D12_INDIRECT_ARGUMENT_TYPE_CONSTANT
        CONSTANT_BUFFER D3D12_INDIRECT_ARGUMENT_TYPE_CONSTANT_BUFFER_VIEW
        SHADER_RESOURCE D3D12_INDIRECT_ARGUMENT_TYPE_SHADER_RESOURCE_VIEW
        UNORDERED_ACCESS D3D12_INDIRECT_ARGUMENT_TYPE_UNORDERED_ACCESS_VIEW
        DISPATCH_RAYS D3D12_INDIRECT_ARGUMENT_TYPE_DISPATCH_RAYS
        DISPATCH_MESH D3D12_INDIRECT_ARGUMENT_TYPE_DISPATCH_MESH
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement indirect argument type done")