
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing depth comparison func")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_DEPTH_COMPARISON_FUNC_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/depth_comparison_func.hpp")
NCPP_SetGlobal(NRHI_DEPTH_COMPARISON_FUNC_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/depth_comparison_func.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_depth_comparison_func"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_DEPTH_COMPARISON_FUNC_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_DEPTH_COMPARISON_FUNC_ENUM_CPP_FILE_PATH}"
    VALUES
        NEVER D3D12_COMPARISON_FUNC_NEVER
        LESS D3D12_COMPARISON_FUNC_LESS
        EQUAL D3D12_COMPARISON_FUNC_EQUAL
        LESS_EQUAL D3D12_COMPARISON_FUNC_LESS_EQUAL
        GREATER D3D12_COMPARISON_FUNC_GREATER
        NOT_EQUAL D3D12_COMPARISON_FUNC_NOT_EQUAL
        GREATER_EQUAL D3D12_COMPARISON_FUNC_GREATER_EQUAL
        ALWAYS D3D12_COMPARISON_FUNC_ALWAYS
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement depth comparison func done")