
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing fence flag")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_FENCE_FLAG_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/fence_flag.hpp")
NCPP_SetGlobal(NRHI_FENCE_FLAG_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/fence_flag.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_fence_flag"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_FENCE_FLAG_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_FENCE_FLAG_ENUM_CPP_FILE_PATH}"
    FLAG_OPERATORS
    VALUES
        NONE D3D12_FENCE_FLAG_NONE
        SHARED D3D12_FENCE_FLAG_SHARED
        SHARED_CROSS_ADAPTER  D3D12_FENCE_FLAG_SHARED_CROSS_ADAPTER
        NON_MONITORED D3D12_FENCE_FLAG_NON_MONITORED
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement fence flag done")