
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing descriptor range type")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_DESCRIPTOR_RANGE_TYPE_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/descriptor_range_type.hpp")
NCPP_SetGlobal(NRHI_DESCRIPTOR_RANGE_TYPE_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/descriptor_range_type.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_descriptor_range_type"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_DESCRIPTOR_RANGE_TYPE_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_DESCRIPTOR_RANGE_TYPE_ENUM_CPP_FILE_PATH}"
    VALUES
        SHADER_RESOURCE D3D12_DESCRIPTOR_RANGE_TYPE_SRV
        UNORDERED_ACCESS D3D12_DESCRIPTOR_RANGE_TYPE_UAV
        CONSTANT_BUFFER D3D12_DESCRIPTOR_RANGE_TYPE_CBV
        SAMPLER D3D12_DESCRIPTOR_RANGE_TYPE_SAMPLER
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement descriptor range type done")