
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing root param type")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_ROOT_PARAM_TYPE_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/root_param_type.hpp")
NCPP_SetGlobal(NRHI_ROOT_PARAM_TYPE_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/root_param_type.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_root_param_type"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_ROOT_PARAM_TYPE_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_ROOT_PARAM_TYPE_ENUM_CPP_FILE_PATH}"
    VALUES
        DESCRIPTOR_TABLE D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE
        CONSTANTS D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS
        CONSTANT_BUFFER D3D12_ROOT_PARAMETER_TYPE_CBV
        SHADER_RESOURCE D3D12_ROOT_PARAMETER_TYPE_SRV
        UNORDERED_ACCESS D3D12_ROOT_PARAMETER_TYPE_UAV
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement root param type done")