
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing enums")

include(NRHI/Drivers/DXGI/FormatHelper)
include(NRHI/Drivers/DirectX12/ImplementRootParamType)
include(NRHI/Drivers/DirectX12/ImplementClearFlag)
include(NRHI/Drivers/DirectX12/ImplementDescriptorHeapType)
include(NRHI/Drivers/DirectX12/ImplementDescriptorHeapFlag)
include(NRHI/Drivers/DirectX12/ImplementDescriptorRangeType)
include(NRHI/Drivers/DirectX12/ImplementCommandListType)
include(NRHI/Drivers/DirectX12/ImplementFenceFlag)
include(NRHI/Drivers/DirectX12/ImplementResourceFlag)
include(NRHI/Drivers/DirectX12/ImplementResourceType)
include(NRHI/Drivers/DirectX12/ImplementResourceState)
include(NRHI/Drivers/DirectX12/ImplementResourceHeapType)
include(NRHI/Drivers/DirectX12/ImplementResourcePlacementAlignment)
include(NRHI/Drivers/DirectX12/ImplementResourceLayout)
include(NRHI/Drivers/DirectX12/ImplementResourceViewType)
include(NRHI/Drivers/DirectX12/ImplementResourceBarrierType)
include(NRHI/Drivers/DirectX12/ImplementResourceBarrierFlag)
include(NRHI/Drivers/DirectX12/ImplementFilter)
include(NRHI/Drivers/DirectX12/ImplementTexCoordAddressMode)
include(NRHI/Drivers/DirectX12/ImplementTextureCopyLocationType)
include(NRHI/Drivers/DirectX12/ImplementPipelineStateType)
include(NRHI/Drivers/DirectX12/ImplementPrimitiveTopology)
include(NRHI/Drivers/DirectX12/ImplementShaderType)
include(NRHI/Drivers/DirectX12/ImplementShaderVisibility)
include(NRHI/Drivers/DirectX12/ImplementRootSignatureFlag)
include(NRHI/Drivers/DirectX12/ImplementCullMode)
include(NRHI/Drivers/DirectX12/ImplementFillMode)
include(NRHI/Drivers/DirectX12/ImplementDepthComparisonFunc)
include(NRHI/Drivers/DirectX12/ImplementBlendFactor)
include(NRHI/Drivers/DirectX12/ImplementBlendOperation)
include(NRHI/Drivers/DirectX12/ImplementColorWriteMode)
include(NRHI/Drivers/DirectX12/ImplementLogicOperation)
include(NRHI/Drivers/DirectX12/ImplementTextureCubeFace)
include(NRHI/Drivers/DirectX12/ImplementInputClassification)
include(NRHI/Drivers/DirectX12/ImplementIndirectArgumentType)
include(NRHI/Drivers/DirectX12/ImplementResourceHeapFlag)



NRHI_DXGI_ImplementFormats(
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement enums done")