
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing state object flag")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_STATE_OBJECT_FLAG_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/state_object_flag.hpp")
NCPP_SetGlobal(NRHI_STATE_OBJECT_FLAG_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/state_object_flag.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_state_object_flag"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_STATE_OBJECT_FLAG_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_STATE_OBJECT_FLAG_ENUM_CPP_FILE_PATH}"
    FLAG_OPERATORS
    VALUES
        NONE D3D12_STATE_OBJECT_FLAG_NONE
        ALLOW_LOCAL_DEPENDENCIES_ON_EXTERNAL_DEFINITIONS D3D12_STATE_OBJECT_FLAG_ALLOW_LOCAL_DEPENDENCIES_ON_EXTERNAL_DEFINITIONS
        ALLOW_EXTERNAL_DEPENDENCIES_ON_LOCAL_DEFINITIONS D3D12_STATE_OBJECT_FLAG_ALLOW_EXTERNAL_DEPENDENCIES_ON_LOCAL_DEFINITIONS
        ALLOW_STATE_OBJECT_ADDITIONS D3D12_STATE_OBJECT_FLAG_ALLOW_STATE_OBJECT_ADDITIONS
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement state object flag done")