
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing resource heap flag")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_RESOURCE_HEAP_FLAG_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_heap_flag.hpp")
NCPP_SetGlobal(NRHI_RESOURCE_HEAP_FLAG_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_heap_flag.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_resource_heap_flag"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_RESOURCE_HEAP_FLAG_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_RESOURCE_HEAP_FLAG_ENUM_CPP_FILE_PATH}"
    FLAG_OPERATORS
    VALUES
        NONE D3D12_HEAP_FLAG_NONE
        SHARED D3D12_HEAP_FLAG_SHARED

        DENY_BUFFERS D3D12_HEAP_FLAG_DENY_BUFFERS

        ALLOW_DISPLAY D3D12_HEAP_FLAG_ALLOW_DISPLAY
        SHARED_CROSS_ADAPTER D3D12_HEAP_FLAG_SHARED_CROSS_ADAPTER

        DENY_RT_DS_TEXTURES D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES
        DENY_NON_RT_DS_TEXTURES D3D12_HEAP_FLAG_DENY_NON_RT_DS_TEXTURES

        HARDWARE_PROTECTED D3D12_HEAP_FLAG_HARDWARE_PROTECTED
        ALLOW_WRITE_WATCH D3D12_HEAP_FLAG_ALLOW_WRITE_WATCH
        ALLOW_SHADER_ATOMICS D3D12_HEAP_FLAG_ALLOW_SHADER_ATOMICS
        CREATE_NOT_RESIDENT D3D12_HEAP_FLAG_CREATE_NOT_RESIDENT
        CREATE_NOT_ZEROED D3D12_HEAP_FLAG_CREATE_NOT_ZEROED

        ALLOW_ALL_BUFFERS_AND_TEXTURES D3D12_HEAP_FLAG_ALLOW_ALL_BUFFERS_AND_TEXTURES
        ALLOW_ONLY_BUFFERS D3D12_HEAP_FLAG_ALLOW_ONLY_BUFFERS
        ALLOW_ONLY_NON_RT_DS_TEXTURES D3D12_HEAP_FLAG_ALLOW_ONLY_NON_RT_DS_TEXTURES
        ALLOW_ONLY_RT_DS_TEXTURES D3D12_HEAP_FLAG_ALLOW_ONLY_RT_DS_TEXTURES
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement resource heap flag done")