
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing resource layout")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_RESOURCE_LAYOUT_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_layout.hpp")
NCPP_SetGlobal(NRHI_RESOURCE_LAYOUT_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_layout.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_resource_layout"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_RESOURCE_LAYOUT_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_RESOURCE_LAYOUT_ENUM_CPP_FILE_PATH}"
    VALUES
        UNKNOWN D3D12_TEXTURE_LAYOUT_UNKNOWN
        ROW_MAJOR D3D12_TEXTURE_LAYOUT_ROW_MAJOR
        _64KB_UNDEFINED_SWIZZLE D3D12_TEXTURE_LAYOUT_64KB_UNDEFINED_SWIZZLE
        _4KB_STANDARD_SWIZZLE D3D12_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement resource layout done")