
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing resource bind flag")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_RESOURCE_BIND_FLAG_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_bind_flag.hpp")
NCPP_SetGlobal(NRHI_RESOURCE_BIND_FLAG_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_bind_flag.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_resource_bind_flag"
    TYPE "ncpp::u64"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_RESOURCE_BIND_FLAG_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_RESOURCE_BIND_FLAG_ENUM_CPP_FILE_PATH}"
    VALUES
        NONE "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(0, 0)"
        VBV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(1, 0)"
        INSTBV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(2, 0)"
        IBV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(3, 0)"
        CBV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(4, 0)"
        SRV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(5, D3D12_RESOURCE_FLAG_DENY_SHADER_RESOURCE)"
        UAV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(6, D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS)"
        RTV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(7, D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET)"
        DSV "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_BIND_FLAG(8, D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL)"
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement resource bind flag done")