
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing resource type")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_RESOURCE_TYPE_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_type.hpp")
NCPP_SetGlobal(NRHI_RESOURCE_TYPE_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_type.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_resource_type"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_RESOURCE_TYPE_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_RESOURCE_TYPE_ENUM_CPP_FILE_PATH}"
    VALUES
        NONE "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(0, D3D12_RESOURCE_DIMENSION_UNKNOWN)"
        BUFFER "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(1, D3D12_RESOURCE_DIMENSION_BUFFER)"
        STRUCTURED_BUFFER "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(2, D3D12_RESOURCE_DIMENSION_BUFFER)"
        INDIRECT_BUFFER "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(3, D3D12_RESOURCE_DIMENSION_BUFFER)"
        TEXTURE_1D "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(4, D3D12_RESOURCE_DIMENSION_TEXTURE1D)"
        TEXTURE_1D_ARRAY "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(5, D3D12_RESOURCE_DIMENSION_TEXTURE1D)"
        TEXTURE_2D "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(6, D3D12_RESOURCE_DIMENSION_TEXTURE2D)"
        TEXTURE_2D_ARRAY "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(7, D3D12_RESOURCE_DIMENSION_TEXTURE2D)"
        TEXTURE_3D "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(8, D3D12_RESOURCE_DIMENSION_TEXTURE3D)"
        TEXTURE_CUBE "NRHI_DRIVER_DIRECTX_12_GENERATE___RESOURCE_TYPE(9, D3D12_RESOURCE_DIMENSION_TEXTURE2D)"
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement resource type done")