
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing root signature flag")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_ROOT_PARAM_TYPE_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/root_signature_flag.hpp")
NCPP_SetGlobal(NRHI_ROOT_PARAM_TYPE_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/root_signature_flag.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_root_signature_flag"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_ROOT_PARAM_TYPE_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_ROOT_PARAM_TYPE_ENUM_CPP_FILE_PATH}"
    VALUES
        NONE D3D12_ROOT_SIGNATURE_FLAG_NONE
        ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT
        DENY_VERTEX_SHADER_ROOT_ACCESS D3D12_ROOT_SIGNATURE_FLAG_DENY_VERTEX_SHADER_ROOT_ACCESS
        DENY_HULL_SHADER_ROOT_ACCESS D3D12_ROOT_SIGNATURE_FLAG_DENY_HULL_SHADER_ROOT_ACCESS
        DENY_DOMAIN_SHADER_ROOT_ACCESS D3D12_ROOT_SIGNATURE_FLAG_DENY_DOMAIN_SHADER_ROOT_ACCESS
        DENY_GEOMETRY_SHADER_ROOT_ACCESS D3D12_ROOT_SIGNATURE_FLAG_DENY_GEOMETRY_SHADER_ROOT_ACCESS
        DENY_PIXEL_SHADER_ROOT_ACCESS D3D12_ROOT_SIGNATURE_FLAG_DENY_PIXEL_SHADER_ROOT_ACCESS
        ALLOW_STREAM_OUTPUT D3D12_ROOT_SIGNATURE_FLAG_ALLOW_STREAM_OUTPUT
        LOCAL_ROOT_SIGNATURE D3D12_ROOT_SIGNATURE_FLAG_LOCAL_ROOT_SIGNATURE
        DENY_AMPLIFICATION_SHADER_ROOT_ACCESS D3D12_ROOT_SIGNATURE_FLAG_DENY_AMPLIFICATION_SHADER_ROOT_ACCESS
        DENY_MESH_SHADER_ROOT_ACCESS D3D12_ROOT_SIGNATURE_FLAG_DENY_MESH_SHADER_ROOT_ACCESS
        CONSTANT_BUFFER_SHADER_RESOURCE_UNORDERED_ACCESS_HEAP_DIRECTLY_INDEXED D3D12_ROOT_SIGNATURE_FLAG_CBV_SRV_UAV_HEAP_DIRECTLY_INDEXED
        SAMPLER_HEAP_DIRECTLY_INDEXED D3D12_ROOT_SIGNATURE_FLAG_SAMPLER_HEAP_DIRECTLY_INDEXED
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement root signature flag done")