
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing shader visibility")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_SHADER_VISIBILITY_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/shader_visibility.hpp")
NCPP_SetGlobal(NRHI_SHADER_VISIBILITY_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/shader_visibility.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_shader_visibility"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_SHADER_VISIBILITY_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_SHADER_VISIBILITY_ENUM_CPP_FILE_PATH}"
    VALUES
        ALL D3D12_SHADER_VISIBILITY_ALL
        VERTEX D3D12_SHADER_VISIBILITY_VERTEX
        TESSELLATION_CONTROL D3D12_SHADER_VISIBILITY_HULL
        TESSELLATION_EVALUATION D3D12_SHADER_VISIBILITY_DOMAIN
        GEOMETRY D3D12_SHADER_VISIBILITY_GEOMETRY
        PIXEL D3D12_SHADER_VISIBILITY_PIXEL
        AMPLIFICATION D3D12_SHADER_VISIBILITY_AMPLIFICATION
        MESH D3D12_SHADER_VISIBILITY_MESH
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement shader visibility done")