
message(STATUS "<NRHI::Drivers::DirectX12> Start implementing resource state")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_RESOURCE_STATE_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_state.hpp")
NCPP_SetGlobal(NRHI_RESOURCE_STATE_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_state.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_resource_state"
    DRIVER_UPPER_CASE_NAME "DIRECTX_12"
    TARGET_HPP_FILE_PATH "${NRHI_RESOURCE_STATE_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_RESOURCE_STATE_ENUM_CPP_FILE_PATH}"
    FLAG_OPERATORS
    VALUES
        COMMON D3D12_RESOURCE_STATE_COMMON
        INPUT_AND_CONSTANT_BUFFER D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER
        INDEX_BUFFER D3D12_RESOURCE_STATE_INDEX_BUFFER
        RENDER_TARGET D3D12_RESOURCE_STATE_RENDER_TARGET
        UNORDERED_ACCESS D3D12_RESOURCE_STATE_UNORDERED_ACCESS
        DEPTH_WRITE D3D12_RESOURCE_STATE_DEPTH_WRITE
        DEPTH_READ D3D12_RESOURCE_STATE_DEPTH_READ
        NON_PIXEL_SHADER_RESOURCE D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE
        PIXEL_SHADER_RESOURCE D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE
        STREAM_OUT D3D12_RESOURCE_STATE_STREAM_OUT
        INDIRECT_ARGUMENT D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT
        COPY_DEST D3D12_RESOURCE_STATE_COPY_DEST
        COPY_SOURCE D3D12_RESOURCE_STATE_COPY_SOURCE
        RESOLVE_DEST D3D12_RESOURCE_STATE_RESOLVE_DEST
        RESOLVE_SOURCE D3D12_RESOURCE_STATE_RESOLVE_SOURCE
        RAYTRACING_ACCELERATION_STRUCTURE D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE
        SHADING_RATE_SOURCE D3D12_RESOURCE_STATE_SHADING_RATE_SOURCE
        _GENERIC_READ D3D12_RESOURCE_STATE_GENERIC_READ
        ALL_SHADER_RESOURCE D3D12_RESOURCE_STATE_ALL_SHADER_RESOURCE
        PRESENT D3D12_RESOURCE_STATE_PRESENT
        PREDICATION D3D12_RESOURCE_STATE_PREDICATION
        VIDEO_DECODE_READ D3D12_RESOURCE_STATE_VIDEO_DECODE_READ
        VIDEO_DECODE_WRITE D3D12_RESOURCE_STATE_VIDEO_DECODE_WRITE
        VIDEO_PROCESS_READ D3D12_RESOURCE_STATE_VIDEO_PROCESS_READ
        VIDEO_PROCESS_WRITE D3D12_RESOURCE_STATE_VIDEO_PROCESS_WRITE
        VIDEO_ENCODE_READ D3D12_RESOURCE_STATE_VIDEO_ENCODE_READ
        VIDEO_ENCODE_WRITE D3D12_RESOURCE_STATE_VIDEO_ENCODE_WRITE
)

message(STATUS "<NRHI::Drivers::DirectX12> Implement resource state done")