
message(STATUS "<NRHI::Drivers::DirectX11> Start implementing depth comparison func")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_DEPTH_COMPARISON_FUNC_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/depth_comparison_func.hpp")
NCPP_SetGlobal(NRHI_DEPTH_COMPARISON_FUNC_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/depth_comparison_func.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_depth_comparison_func"
    DRIVER_UPPER_CASE_NAME "DIRECTX_11"
    TARGET_HPP_FILE_PATH "${NRHI_DEPTH_COMPARISON_FUNC_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_DEPTH_COMPARISON_FUNC_ENUM_CPP_FILE_PATH}"
    VALUES
        NEVER D3D11_COMPARISON_NEVER
        LESS D3D11_COMPARISON_LESS
        EQUAL D3D11_COMPARISON_EQUAL
        LESS_EQUAL D3D11_COMPARISON_LESS_EQUAL
        GREATER D3D11_COMPARISON_GREATER
        NOT_EQUAL D3D11_COMPARISON_NOT_EQUAL
        GREATER_EQUAL D3D11_COMPARISON_GREATER_EQUAL
        ALWAYS D3D11_COMPARISON_ALWAYS
)

message(STATUS "<NRHI::Drivers::DirectX11> Implement depth comparison func done")