
message(STATUS "<NRHI::Drivers::DirectX11> Start implementing blend factor")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_BLEND_FACTOR_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/blend_factor.hpp")
NCPP_SetGlobal(NRHI_BLEND_FACTOR_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/blend_factor.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_blend_factor"
    DRIVER_UPPER_CASE_NAME "DIRECTX_11"
    TARGET_HPP_FILE_PATH "${NRHI_BLEND_FACTOR_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_BLEND_FACTOR_ENUM_CPP_FILE_PATH}"
    VALUES
        ZERO D3D11_BLEND_ZERO
        ONE D3D11_BLEND_ONE
        SRC_COLOR D3D11_BLEND_SRC_COLOR
        INV_SRC_COLOR D3D11_BLEND_INV_SRC_COLOR
        SRC_ALPHA D3D11_BLEND_SRC_ALPHA
        INV_SRC_ALPHA D3D11_BLEND_INV_SRC_ALPHA
        DEST_ALPHA D3D11_BLEND_DEST_ALPHA
        INV_DEST_ALPHA D3D11_BLEND_INV_DEST_ALPHA
        DEST_COLOR D3D11_BLEND_DEST_COLOR
        INV_DEST_COLOR D3D11_BLEND_INV_DEST_COLOR
        SRC_ALPHA_SAT D3D11_BLEND_SRC_ALPHA_SAT
        BLEND_FACTOR D3D11_BLEND_BLEND_FACTOR
        INV_BLEND_FACTOR D3D11_BLEND_INV_BLEND_FACTOR
        SRC1_COLOR D3D11_BLEND_SRC1_COLOR
        INV_SRC1_COLOR D3D11_BLEND_INV_SRC1_COLOR
        SRC1_ALPHA D3D11_BLEND_SRC1_ALPHA
        INV_SRC1_ALPHA D3D11_BLEND_INV_SRC1_ALPHA
)

message(STATUS "<NRHI::Drivers::DirectX11> Implement blend factor done")