
message(STATUS "<NRHI::Drivers::DirectX11> Start implementing resource type")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_RESOURCE_TYPE_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_type.hpp")
NCPP_SetGlobal(NRHI_RESOURCE_TYPE_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_type.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "E_resource_type"
    DRIVER_UPPER_CASE_NAME "DIRECTX_11"
    TARGET_HPP_FILE_PATH "${NRHI_RESOURCE_TYPE_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_RESOURCE_TYPE_ENUM_CPP_FILE_PATH}"
    VALUES
        NONE 0
        BUFFER D3D11_SRV_DIMENSION_BUFFER
        TEXTURE_1D D3D11_SRV_DIMENSION_TEXTURE1D
        TEXTURE_1D_ARRAY D3D11_SRV_DIMENSION_TEXTURE1DARRAY
        TEXTURE_2D D3D11_SRV_DIMENSION_TEXTURE2D
        TEXTURE_2D_ARRAY D3D11_SRV_DIMENSION_TEXTURE2DARRAY
        TEXTURE_3D D3D11_SRV_DIMENSION_TEXTURE3D
)

message(STATUS "<NRHI::Drivers::DirectX11> Implement resource type done")