
message(STATUS "<NRHI::Drivers::DirectX11> Start implementing resource bind flag")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_RESOURCE_BIND_FLAG_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_bind_flag.hpp")
NCPP_SetGlobal(NRHI_RESOURCE_BIND_FLAG_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/resource_bind_flag.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_resource_bind_flag"
    TYPE "ncpp::u32"
    DRIVER_UPPER_CASE_NAME "DIRECTX_11"
    TARGET_HPP_FILE_PATH "${NRHI_RESOURCE_BIND_FLAG_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_RESOURCE_BIND_FLAG_ENUM_CPP_FILE_PATH}"
    VALUES
        NONE 0
        INPUT_BUFFER D3D11_BIND_VERTEX_BUFFER
        INPUT_BUFFER D3D11_BIND_VERTEX_BUFFER
        INDEX_BUFFER D3D11_BIND_INDEX_BUFFER
        CONSTANT_BUFFER D3D11_BIND_CONSTANT_BUFFER
        SHADER_RESOURCE D3D11_BIND_SHADER_RESOURCE
        UNORDERED_ACCESS D3D11_BIND_UNORDERED_ACCESS
        RENDER_TARGET D3D11_BIND_RENDER_TARGET
        DEPTH_STENCIL D3D11_BIND_DEPTH_STENCIL
)

message(STATUS "<NRHI::Drivers::DirectX11> Implement resource bind flag done")