
message(STATUS "<NRHI::Drivers::DirectX11> Start implementing texture cube face")

include(NRHI/Utilities/EnumHelper)



NCPP_SetGlobal(NRHI_TEXTURE_CUBE_FACE_ENUM_HPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/texture_cube_face.hpp")
NCPP_SetGlobal(NRHI_TEXTURE_CUBE_FACE_ENUM_CPP_FILE_PATH "${NRHI_GENERATED_FILES_DIR}/texture_cube_face.cpp")



NRHI_EnumHelper_CreateEnum(
    NAMESPACE "nrhi"
    NAME "ED_texture_cube_face"
    DRIVER_UPPER_CASE_NAME "DIRECTX_11"
    TARGET_HPP_FILE_PATH "${NRHI_TEXTURE_CUBE_FACE_ENUM_HPP_FILE_PATH}"
    TARGET_CPP_FILE_PATH "${NRHI_TEXTURE_CUBE_FACE_ENUM_CPP_FILE_PATH}"
    VALUES
        RIGHT D3D11_TEXTURECUBE_FACE_POSITIVE_X
        LEFT D3D11_TEXTURECUBE_FACE_NEGATIVE_X
        UP D3D11_TEXTURECUBE_FACE_POSITIVE_Y
        DOWN D3D11_TEXTURECUBE_FACE_NEGATIVE_Y
        FORWARD D3D11_TEXTURECUBE_FACE_POSITIVE_Z
        BACK D3D11_TEXTURECUBE_FACE_NEGATIVE_Z
)

message(STATUS "<NRHI::Drivers::DirectX11> Implement texture cube face done")